//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_default : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean InteractUI
        {
            get
            {
                return SteamVR_Actions.default_InteractUI;
            }
        }
        
        public virtual SteamVR_Action_Boolean Teleport
        {
            get
            {
                return SteamVR_Actions.default_Teleport;
            }
        }
        
        public virtual SteamVR_Action_Boolean GrabPinch
        {
            get
            {
                return SteamVR_Actions.default_GrabPinch;
            }
        }
        
        public virtual SteamVR_Action_Boolean GrabGrip
        {
            get
            {
                return SteamVR_Actions.default_GrabGrip;
            }
        }
        
        public virtual SteamVR_Action_Pose Pose
        {
            get
            {
                return SteamVR_Actions.default_Pose;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonLeftHand
        {
            get
            {
                return SteamVR_Actions.default_SkeletonLeftHand;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonRightHand
        {
            get
            {
                return SteamVR_Actions.default_SkeletonRightHand;
            }
        }
        
        public virtual SteamVR_Action_Single Squeeze
        {
            get
            {
                return SteamVR_Actions.default_Squeeze;
            }
        }
        
        public virtual SteamVR_Action_Boolean HeadsetOnHead
        {
            get
            {
                return SteamVR_Actions.default_HeadsetOnHead;
            }
        }
        
        public virtual SteamVR_Action_Boolean SnapTurnLeft
        {
            get
            {
                return SteamVR_Actions.default_SnapTurnLeft;
            }
        }
        
        public virtual SteamVR_Action_Boolean SnapTurnRight
        {
            get
            {
                return SteamVR_Actions.default_SnapTurnRight;
            }
        }
        
        public virtual SteamVR_Action_Vector2 touchpad
        {
            get
            {
                return SteamVR_Actions.default_touchpad;
            }
        }
        
        public virtual SteamVR_Action_Boolean buttonY
        {
            get
            {
                return SteamVR_Actions.default_buttonY;
            }
        }
        
        public virtual SteamVR_Action_Vector2 touchright
        {
            get
            {
                return SteamVR_Actions.default_touchright;
            }
        }
        
        public virtual SteamVR_Action_Boolean buttonX
        {
            get
            {
                return SteamVR_Actions.default_buttonX;
            }
        }
        
        public virtual SteamVR_Action_Boolean buttno_freez_x
        {
            get
            {
                return SteamVR_Actions.default_buttno_freez_x;
            }
        }
        
        public virtual SteamVR_Action_Boolean buttno_freez_y
        {
            get
            {
                return SteamVR_Actions.default_buttno_freez_y;
            }
        }
        
        public virtual SteamVR_Action_Boolean buttno_freez_z
        {
            get
            {
                return SteamVR_Actions.default_buttno_freez_z;
            }
        }
        
        public virtual SteamVR_Action_Vector3 hand_pos_left
        {
            get
            {
                return SteamVR_Actions.default_hand_pos_left;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.default_Haptic;
            }
        }
    }
}
